INFO - SimCLR - Running command 'main'
INFO - SimCLR - Started run with ID "1386"
==== Starting to save features ===
Successfully loaded labels from /project/schirris/basisscripts/step_3/data_basis_brca_with_labels_and_splits.csv, it has 1018508 files.
We use a train split of fold 1 of 431635 files.
Successfully loaded labels from /project/schirris/basisscripts/step_3/data_basis_brca_with_labels_and_splits.csv, it has 1018508 files.
We use a test split of fold 1 of 156968 files.
Successfully loaded labels from /project/schirris/basisscripts/step_3/data_basis_brca_with_labels_and_splits.csv, it has 1018508 files.
We use a val split of fold 1 of 106867 files.
ERROR - SimCLR - Failed after 0:00:04!
Traceback (most recent calls WITHOUT Sacred internals):
  File "/home/yonis/SimCLR-1/msidata/save_feature_vectors.py", line 253, in main
    simclr_model, _, _ = load_model(args, train_loader, reload_model=True)
TypeError: load_model() got multiple values for argument 'reload_model'

